// Generated by gencpp from file lstm_visual_servoing/Control.msg
// DO NOT EDIT!


#ifndef LSTM_VISUAL_SERVOING_MESSAGE_CONTROL_H
#define LSTM_VISUAL_SERVOING_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lstm_visual_servoing
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : header()
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)
    , claw(0.0)  {
    }
  Control_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , rx(0.0)
    , ry(0.0)
    , rz(0.0)
    , claw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;

   typedef double _rx_type;
  _rx_type rx;

   typedef double _ry_type;
  _ry_type ry;

   typedef double _rz_type;
  _rz_type rz;

   typedef double _claw_type;
  _claw_type claw;





  typedef boost::shared_ptr< ::lstm_visual_servoing::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lstm_visual_servoing::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::lstm_visual_servoing::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::lstm_visual_servoing::Control > ControlPtr;
typedef boost::shared_ptr< ::lstm_visual_servoing::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lstm_visual_servoing::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lstm_visual_servoing::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lstm_visual_servoing::Control_<ContainerAllocator1> & lhs, const ::lstm_visual_servoing::Control_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.rx == rhs.rx &&
    lhs.ry == rhs.ry &&
    lhs.rz == rhs.rz &&
    lhs.claw == rhs.claw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lstm_visual_servoing::Control_<ContainerAllocator1> & lhs, const ::lstm_visual_servoing::Control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lstm_visual_servoing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lstm_visual_servoing::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lstm_visual_servoing::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lstm_visual_servoing::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lstm_visual_servoing::Control_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lstm_visual_servoing::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lstm_visual_servoing::Control_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lstm_visual_servoing::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4252f55009d0a673f8e602b0ed6fd8d2";
  }

  static const char* value(const ::lstm_visual_servoing::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4252f55009d0a673ULL;
  static const uint64_t static_value2 = 0xf8e602b0ed6fd8d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::lstm_visual_servoing::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lstm_visual_servoing/Control";
  }

  static const char* value(const ::lstm_visual_servoing::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lstm_visual_servoing::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 vx\n"
"float64 vy\n"
"float64 vz\n"
"float64 rx\n"
"float64 ry\n"
"float64 rz\n"
"float64 claw\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lstm_visual_servoing::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lstm_visual_servoing::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.rx);
      stream.next(m.ry);
      stream.next(m.rz);
      stream.next(m.claw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lstm_visual_servoing::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lstm_visual_servoing::Control_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
    s << indent << "rx: ";
    Printer<double>::stream(s, indent + "  ", v.rx);
    s << indent << "ry: ";
    Printer<double>::stream(s, indent + "  ", v.ry);
    s << indent << "rz: ";
    Printer<double>::stream(s, indent + "  ", v.rz);
    s << indent << "claw: ";
    Printer<double>::stream(s, indent + "  ", v.claw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSTM_VISUAL_SERVOING_MESSAGE_CONTROL_H
