// Generated by gencpp from file lstm_visual_servoing/Recorder.msg
// DO NOT EDIT!


#ifndef LSTM_VISUAL_SERVOING_MESSAGE_RECORDER_H
#define LSTM_VISUAL_SERVOING_MESSAGE_RECORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lstm_visual_servoing
{
template <class ContainerAllocator>
struct Recorder_
{
  typedef Recorder_<ContainerAllocator> Type;

  Recorder_()
    : header()
    , record(false)
    , save(false)
    , clear(false)  {
    }
  Recorder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , record(false)
    , save(false)
    , clear(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _record_type;
  _record_type record;

   typedef uint8_t _save_type;
  _save_type save;

   typedef uint8_t _clear_type;
  _clear_type clear;





  typedef boost::shared_ptr< ::lstm_visual_servoing::Recorder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lstm_visual_servoing::Recorder_<ContainerAllocator> const> ConstPtr;

}; // struct Recorder_

typedef ::lstm_visual_servoing::Recorder_<std::allocator<void> > Recorder;

typedef boost::shared_ptr< ::lstm_visual_servoing::Recorder > RecorderPtr;
typedef boost::shared_ptr< ::lstm_visual_servoing::Recorder const> RecorderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lstm_visual_servoing::Recorder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lstm_visual_servoing::Recorder_<ContainerAllocator1> & lhs, const ::lstm_visual_servoing::Recorder_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.record == rhs.record &&
    lhs.save == rhs.save &&
    lhs.clear == rhs.clear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lstm_visual_servoing::Recorder_<ContainerAllocator1> & lhs, const ::lstm_visual_servoing::Recorder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lstm_visual_servoing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lstm_visual_servoing::Recorder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lstm_visual_servoing::Recorder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lstm_visual_servoing::Recorder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f146743ee93cda48244d1ec7146e2e0b";
  }

  static const char* value(const ::lstm_visual_servoing::Recorder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf146743ee93cda48ULL;
  static const uint64_t static_value2 = 0x244d1ec7146e2e0bULL;
};

template<class ContainerAllocator>
struct DataType< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lstm_visual_servoing/Recorder";
  }

  static const char* value(const ::lstm_visual_servoing::Recorder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool record\n"
"bool save\n"
"bool clear\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::lstm_visual_servoing::Recorder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.record);
      stream.next(m.save);
      stream.next(m.clear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Recorder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lstm_visual_servoing::Recorder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lstm_visual_servoing::Recorder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "record: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.record);
    s << indent << "save: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.save);
    s << indent << "clear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.clear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSTM_VISUAL_SERVOING_MESSAGE_RECORDER_H
