FROM cuda-ros-noetic-desktop-full

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y -qq\
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    build-essential \
    usbutils \
    udev \
    cheese

RUN apt install -y \
    python3-pip

COPY requirements.txt /opt/app/requirements.txt
WORKDIR /opt/app
RUN pip install -r requirements.txt
COPY . /opt/app

RUN echo "source /root/setup_script.bash" >> /root/.bashrc

ENTRYPOINT /bin/bash
